#+title: My homepage with org-mode
#+author: Duncan Mac-Vicar P.
#+date: <2019-08-15 Thu>

* Introduction

This setup based on [[https://orgmode.org][org-mode]] aims to replace my previous [[https://jekyllrb.com][Jekyll]] setup used to publish my site.

* Implementation

For details about the implementation see [[file:posts/2019-09-03-migrating-from-jekyll-to-org/index.org][the introductory post]] and the [[https://github.com/dmacvicar/site.org][\faGithub Source]].

* Usage

- Posts go into =posts/=
  Preferably in their own subdirectory together with all their assets (self-contained)
- Tutorials go in =tutorials/=, as they are rendered (for now) with the [[https://github.com/fniessen/org-html-themes][readtheorg]] theme

To generate:

#+BEGIN_EXAMPLE
$ make
#+END_EXAMPLE

The output site will be rendered in =public/=.

* Features

*** Redirection

  When the site was generated using Jekyll, posts where generated in the =/:year/:month/:day/:id.html= route.
  In order to generate a redirect page, use the following keyword to generate a redirect page:

  #+BEGIN_SRC org
  #+REDIRECT_FROM /old/url/index.html
  #+END_SRC

** Drafts

 To hide a post from the list of recent posts or the full archive, use:

  #+BEGIN_SRC org
  #+DRAFT t
  #+END_SRC
 
  Note that the post will still be published, but you will need to access it by its URL directly.

* License

The code used for generating the site is licensed under the [[file:LICENSE][MIT]] license.

The content of the site, Copyright (©) 2014-2019 {{{author}}}.
