#+TITLE: LISTEN I HAVE MY RIGHTS!!!!
#+DATE: <2006-10-31 Tue>
#+REDIRECT_FROM: /2006/10/31/listen-i-have-my-rights.html

Participating in a opensource community has lot of advantages, you get to know really cool people. You learn lot of new things... but also strange anecdotes happen.

Some time ago I was talking with [[https://twitter.com/wstephenson][Will]], and we both remembered one of the most funniest (now) things ever happened in =#kopete= irc channel. We laughed a lot, until Will told me. "I still have those logs somewhere". I said "Really! I think it is time to blog them.

April 3, probably 2003 or 2004. I was in Chile by then. It was sleeping time for Europa. In the channel you can see Sean Egan, GAIM's lead developer, and myself. Until....

The following takes place between 5 am and 6 am... Events ocur in real time.

#+BEGIN_EXAMPLE
  --> Lazlo ([HOST REMOVED].edu) has joined #kopete
  <Lazlo> uhh, hi all heh. I have a strange request. is that Sean Egan
  from New York (sorry kinda new to irc)
  <SeanEgan> hm?
  <Lazlo> hello ?
  <Lazlo> oh heh
  <SeanEgan> Um, yeah. I'm from New York
  <Lazlo> uh, hi -- I searched on google and it said a 'Sean Egan' was in
  this chat room. Do you know where Valley STream is?
  <SeanEgan> Yeah, that's where I live on Long Island
  <Lazlo> ehh, what's the zip code heh (sorry for these odd questions I have
  to protect an identity here, kinda iffy)?
  <SeanEgan> hehe, um, it's [ZIP CODE REMOVED]. Who are you?
  <Lazlo> uh, Are you at [ADDRESS REMOVED]?
  <SeanEgan> ok. Who are you?
  <Lazlo> can anyone here tell me if this is really Sean Egan?
  <SeanEgan> they're probably all asleep. This is a very European channel.
  <SeanEgan> being KDE and all ;)
  <Lazlo> uhh, hi all heh. I have a strange request. is that Sean Egan
  from New York (sorry
  <Lazlo> um, what's KDE? I don't use computers mujch
  <SeanEgan> It's alright. Why do you know m address?
  <Lazlo> whatever man -- look, are you really Sean Egan?
  <SeanEgan> Yeah.
  <Lazlo> um, I think I may have found your wallet near a truck stop
  <SeanEgan> really?!
  <SeanEgan> haha!
  <SeanEgan> I lost my wallet yesterda
  <SeanEgan> y
  <Lazlo> phew! hah, man i wasn't sure if I could find you heh
  <SeanEgan> well, you do have my address ;)
  <Lazlo> heh, true but i'm in west virginia. you're credit card is [CREDIT
  CARD REMOVED], right?
  <SeanEgan> ,,,
  <SeanEgan> Um, I'll take your word for it...
  <Lazlo> ?? heh, maybe I should buy some stuff haha
  * SeanEgan hopes you're joking.
  <SeanEgan> Ok. The address you have is my Long Island address, but I'm up
  at school in Binghamton
  <Lazlo> um, i can rent a car with the credit card and drive to drop it off
  if you like?
  <Lazlo> by the way, who's the hot girl in the picture ;-) heh
  <SeanEgan> Dude, that's my sister.
  <SeanEgan> Listen, just mail the wallet to me. I'll PM you my address.
  <Lazlo> man just calm down -- i'm trying to help here i didn't know
  <Lazlo> what about the cost to send it?!?
  <SeanEgan> no, it's alright. I'm going to PM you my address, and you can
  mail it to me?
  <SeanEgan> Um... I don't know. Maybe $2?
  <Lazlo> $2?!? i think more than that man
  <SeanEgan> If you want, I should have some cash in there, you can pay with
  my money.
  <SeanEgan> But I need my id and my credit cards and stuff.
  <Lazlo> look i took the time to search your name and stuff
  <SeanEgan> yeah, pay for postage with my own money, I don't care
  <Lazlo> i'm not even talking about postage man -- I'll use the card to buy
  stuff I think is right, seriously. you owe me big time
  <SeanEgan> you want a reward?
  <SeanEgan> How much cash do I have in there? $30?
  <duncanmv> oh, Americans
  <Lazlo> whatever dude -- you don't get it! How much do you have on your
  card, can i buy some stuff?
  <SeanEgan> No, you can't
  <SeanEgan> Are you serious?
  * duncanmv doesn't find it a funny joke
  <Lazlo> why wouldl i joke?! look, i'll just buy some stuff or you won't
  get your wallet
  <SeanEgan> Lazlo: I just called my bank and they've cancelled the credit
  card.
  <SeanEgan> I'll let you keep all the cash I have in there as a reward, but
  if you would please return it to the address I PMed you, I would really
  appreciate it.
  <Lazlo> ??!?!?
  <SeanEgan> And so would the Occidental University Police, if you catch my
  drift.
  <Lazlo> now you WONT GET YOUR FRIGGIN WALLET
  <Lazlo> uHGHGHG
  <duncanmv> ok, just call his college tomorrow
  <duncanmv> and tell them [NAME REMOVED] has your wallet
  <duncanmv> tell them the ip and time log
  <duncanmv> and tell them you offered him even a reward
  <SeanEgan> Lazlo: Let's not make a big deal out of it. Keep the cash, and
  mail the wallet to that address, ok?
  <Lazlo> what the f*XCKC wahta kinda platce is this??!? stay out of
  this duncanmv. dude don't you DARE TELL MY schools
  <Lazlo> SeanEgan: NO! crap there's only $24 dollars in the WALLET man
  <SeanEgan> Listen, that wallet has my drivers license in it, it has my
  social security card, it has my school id... I really need that.
  <SeanEgan> You can keep the $24, just mail it back to me, please.
  <SeanEgan> What do you think is a fair reward?
  <Lazlo> F*CUI@ NO!!! look, i could have sold your stuff already but i
  didn't. social security cards are expensive
  <SeanEgan> Listen, how much do you want from me?
  <duncanmv> I could have sold your social security card? wtf? gansters?
  <Lazlo> LISTEN! I'm talking a few hundred dude -- and some stuff.
  <Lazlo> all i know is the people on the internet always look for this
  identify stuff
  <SeanEgan> It's not worth a few hundred to me. I can just get the ID
  reissued for a hundred.
  <SeanEgan> at most
  <SeanEgan> OK, and you just told me that you're selling my social security
  number, so I can get new one and make sure it's worthless.
  <SeanEgan> I'll offer you $100.
  <SeanEgan> final offer.
  <Lazlo> F@#@! FINE dude, whatever -- how will you send me the money then?
  i definitely WONT send it until the money gets here. i'm no fool buddy
  <duncanmv> ok
  <duncanmv> I logged into [UNIVERSITY NAME REMOVED], and got all his data
  <duncanmv> ;)
  <SeanEgan> My ATM pin is [PIN REMOVED]. That's the Citibank one. If you
  withdraw anymore than $100, I report you to the police and they'll have your
  picture and everything and you'll go to jail, do you understand me?
  <SeanEgan> Also, I'm changing the PIN FIRST THING tomorrow, so you have to
  act on that quick.
  <SeanEgan> deal?
  <Lazlo> This is some world of shit dudes! i try to help and all you do is
  threaten police call!!@@ LISTEN I HAVE MY RIGHTS
  <SeanEgan> Lazlo: You have no clue how deep trouble you're in right now.
  <duncanmv> your rights is stealing Sean's money? come on
  <SeanEgan> 10 people have this conversation logged; we have all your
  personal data; you really are in no position to talk about your rights.
  <Lazlo> WHATEVER This is the LAST time i try to help some looser out who
  can't keep his wallet. Where's your gratitude man?
  <SeanEgan> Ok. Take $100. Send me my wallet.
  <Lazlo> f&%@ fine. you're lucky.
  <-- Lazlo has quit ("leaving")
#+END_EXAMPLE

I never knew what happened with Sean's wallet. So today I emailed him and asked. This is the happy end of the story:

#+BEGIN_QUOTE
  Ha! I didn't think anyone remembered that! That guy was nuts. I was\\
  able to reason with him, though. It turned out I was able to promise\\
  him a feature request in Gaim and that sufficed for him. He sent the\\
  wallet back, and I never found any weird fraudulent charges on any
  of\\
  my cards ;)

  My guess is that he wasn't any older than 16.

  Just remember, every time a Gaim user sends someone a file by
  dragging\\
  it into a conversation window, it's because I lost my wallet.

  -s.
#+END_QUOTE
